export const WORLDS_COUNTRIES = [
  { country: "Afghanistan", iso2: "AF", iso3: "AFG", phoneCode: "+93" },
  { country: "Albania", iso2: "AL", iso3: "ALB", phoneCode: "+355" },
  { country: "Algeria", iso2: "DZ", iso3: "DZA", phoneCode: "+213" },
  { country: "American Samoa", iso2: "AS", iso3: "ASM", phoneCode: "+1" },
  { country: "Andorra", iso2: "AD", iso3: "AND", phoneCode: "+376" },
  { country: "Angola", iso2: "AO", iso3: "AGO", phoneCode: "+244" },
  { country: "Anguilla", iso2: "AI", iso3: "AIA", phoneCode: "+1" },
  { country: "Antarctica", iso2: "AQ", iso3: "ATA", phoneCode: "+672" },
  { country: "Antigua and Barbuda", iso2: "AG", iso3: "ATG", phoneCode: "+1" },
  { country: "Argentina", iso2: "AR", iso3: "ARG", phoneCode: "+54" },
  { country: "Armenia", iso2: "AM", iso3: "ARM", phoneCode: "+374" },
  { country: "Aruba", iso2: "AW", iso3: "ABW", phoneCode: "+297" },
  { country: "Australia", iso2: "AU", iso3: "AUS", phoneCode: "+61" },
  { country: "Austria", iso2: "AT", iso3: "AUT", phoneCode: "+43" },
  { country: "Azerbaijan", iso2: "AZ", iso3: "AZE", phoneCode: "+994" },
  { country: "Bahamas", iso2: "BS", iso3: "BHS", phoneCode: "+1" },
  { country: "Bahrain", iso2: "BH", iso3: "BHR", phoneCode: "+973" },
  { country: "Bangladesh", iso2: "BD", iso3: "BGD", phoneCode: "+880" },
  { country: "Barbados", iso2: "BB", iso3: "BRB", phoneCode: "+1" },
  { country: "Belarus", iso2: "BY", iso3: "BLR", phoneCode: "+375" },
  { country: "Belgium", iso2: "BE", iso3: "BEL", phoneCode: "+32" },
  { country: "Belize", iso2: "BZ", iso3: "BLZ", phoneCode: "+501" },
  { country: "Benin", iso2: "BJ", iso3: "BEN", phoneCode: "+229" },
  { country: "Bermuda", iso2: "BM", iso3: "BMU", phoneCode: "+1" },
  { country: "Bhutan", iso2: "BT", iso3: "BTN", phoneCode: "+975" },
  { country: "Bolivia", iso2: "BO", iso3: "BOL", phoneCode: "+591" },
  { country: "Bosnia and Herzegovina", iso2: "BA", iso3: "BIH", phoneCode: "+387" },
  { country: "Botswana", iso2: "BW", iso3: "BWA", phoneCode: "+267" },
  { country: "Brazil", iso2: "BR", iso3: "BRA", phoneCode: "+55" },
  { country: "British Indian Ocean Territory", iso2: "IO", iso3: "IOT", phoneCode: "+246" },
  { country: "British Virgin Islands", iso2: "VG", iso3: "VGB", phoneCode: "+1" },
  { country: "Brunei", iso2: "BN", iso3: "BRN", phoneCode: "+673" },
  { country: "Bulgaria", iso2: "BG", iso3: "BGR", phoneCode: "+359" },
  { country: "Burkina Faso", iso2: "BF", iso3: "BFA", phoneCode: "+226" },
  { country: "Burundi", iso2: "BI", iso3: "BDI", phoneCode: "+257" },
  { country: "Cambodia", iso2: "KH", iso3: "KHM", phoneCode: "+855" },
  { country: "Cameroon", iso2: "CM", iso3: "CMR", phoneCode: "+237" },
  { country: "Canada", iso2: "CA", iso3: "CAN", phoneCode: "+1" },
  { country: "Cape Verde", iso2: "CV", iso3: "CPV", phoneCode: "+238" },
  { country: "Cayman Islands", iso2: "KY", iso3: "CYM", phoneCode: "+1" },
  { country: "Central African Republic", iso2: "CF", iso3: "CAF", phoneCode: "+236" },
  { country: "Chad", iso2: "TD", iso3: "TCD", phoneCode: "+235" },
  { country: "Chile", iso2: "CL", iso3: "CHL", phoneCode: "+56" },
  { country: "China", iso2: "CN", iso3: "CHN", phoneCode: "+86" },
  { country: "Christmas Island", iso2: "CX", iso3: "CXR", phoneCode: "+61" },
  { country: "Cocos Islands", iso2: "CC", iso3: "CCK", phoneCode: "+61" },
  { country: "Colombia", iso2: "CO", iso3: "COL", phoneCode: "+57" },
  { country: "Comoros", iso2: "KM", iso3: "COM", phoneCode: "+269" },
  { country: "Cook Islands", iso2: "CK", iso3: "COK", phoneCode: "+682" },
  { country: "Costa Rica", iso2: "CR", iso3: "CRI", phoneCode: "+506" },
  { country: "Croatia", iso2: "HR", iso3: "HRV", phoneCode: "+385" },
  { country: "Cuba", iso2: "CU", iso3: "CUB", phoneCode: "+53" },
  { country: "Curacao", iso2: "CW", iso3: "CUW", phoneCode: "+599" },
  { country: "Cyprus", iso2: "CY", iso3: "CYP", phoneCode: "+357" },
  { country: "Czech Republic", iso2: "CZ", iso3: "CZE", phoneCode: "+420" },
  { country: "Democratic Republic of the Congo", iso2: "CD", iso3: "COD", phoneCode: "+243" },
  { country: "Denmark", iso2: "DK", iso3: "DNK", phoneCode: "+45" },
  { country: "Djibouti", iso2: "DJ", iso3: "DJI", phoneCode: "+253" },
  { country: "Dominica", iso2: "DM", iso3: "DMA", phoneCode: "+1" },
  { country: "Dominican Republic", iso2: "DO", iso3: "DOM", phoneCode: "+1" },
  { country: "East Timor", iso2: "TL", iso3: "TLS", phoneCode: "+670" },
  { country: "Ecuador", iso2: "EC", iso3: "ECU", phoneCode: "+593" },
  { country: "Egypt", iso2: "EG", iso3: "EGY", phoneCode: "+20" },
  { country: "El Salvador", iso2: "SV", iso3: "SLV", phoneCode: "+503" },
  { country: "Equatorial Guinea", iso2: "GQ", iso3: "GNQ", phoneCode: "+240" },
  { country: "Eritrea", iso2: "ER", iso3: "ERI", phoneCode: "+291" },
  { country: "Estonia", iso2: "EE", iso3: "EST", phoneCode: "+372" },
  { country: "Ethiopia", iso2: "ET", iso3: "ETH", phoneCode: "+251" },
  { country: "Falkland Islands", iso2: "FK", iso3: "FLK", phoneCode: "+500" },
  { country: "Faroe Islands", iso2: "FO", iso3: "FRO", phoneCode: "+298" },
  { country: "Fiji", iso2: "FJ", iso3: "FJI", phoneCode: "+679" },
  { country: "Finland", iso2: "FI", iso3: "FIN", phoneCode: "+358" },
  { country: "France", iso2: "FR", iso3: "FRA", phoneCode: "+33" },
  { country: "French Polynesia", iso2: "PF", iso3: "PYF", phoneCode: "+689" },
  { country: "Gabon", iso2: "GA", iso3: "GAB", phoneCode: "+241" },
  { country: "Gambia", iso2: "GM", iso3: "GMB", phoneCode: "+220" },
  { country: "Georgia", iso2: "GE", iso3: "GEO", phoneCode: "+995" },
  { country: "Germany", iso2: "DE", iso3: "DEU", phoneCode: "+49" },
  { country: "Ghana", iso2: "GH", iso3: "GHA", phoneCode: "+233" },
  { country: "Gibraltar", iso2: "GI", iso3: "GIB", phoneCode: "+350" },
  { country: "Greece", iso2: "GR", iso3: "GRC", phoneCode: "+30" },
  { country: "Greenland", iso2: "GL", iso3: "GRL", phoneCode: "+299" },
  { country: "Grenada", iso2: "GD", iso3: "GRD", phoneCode: "+1" },
  { country: "Guam", iso2: "GU", iso3: "GUM", phoneCode: "+1" },
  { country: "Guatemala", iso2: "GT", iso3: "GTM", phoneCode: "+502" },
  { country: "Guernsey", iso2: "GG", iso3: "GGY", phoneCode: "+44" },
  { country: "Guinea", iso2: "GN", iso3: "GIN", phoneCode: "+224" },
  { country: "Guinea-Bissau", iso2: "GW", iso3: "GNB", phoneCode: "+245" },
  { country: "Guyana", iso2: "GY", iso3: "GUY", phoneCode: "+592" },
  { country: "Haiti", iso2: "HT", iso3: "HTI", phoneCode: "+509" },
  { country: "Honduras", iso2: "HN", iso3: "HND", phoneCode: "+504" },
  { country: "Hong Kong", iso2: "HK", iso3: "HKG", phoneCode: "+852" },
  { country: "Hungary", iso2: "HU", iso3: "HUN", phoneCode: "+36" },
  { country: "Iceland", iso2: "IS", iso3: "ISL", phoneCode: "+354" },
  { country: "India", iso2: "IN", iso3: "IND", phoneCode: "+91" },
  { country: "Indonesia", iso2: "ID", iso3: "IDN", phoneCode: "+62" },
  { country: "Iran", iso2: "IR", iso3: "IRN", phoneCode: "+98" },
  { country: "Iraq", iso2: "IQ", iso3: "IRQ", phoneCode: "+964" },
  { country: "Ireland", iso2: "IE", iso3: "IRL", phoneCode: "+353" },
  { country: "Isle of Man", iso2: "IM", iso3: "IMN", phoneCode: "+44" },
  { country: "Israel", iso2: "IL", iso3: "ISR", phoneCode: "+972" },
  { country: "Italy", iso2: "IT", iso3: "ITA", phoneCode: "+39" },
  { country: "Ivory Coast", iso2: "CI", iso3: "CIV", phoneCode: "+225" },
  { country: "Jamaica", iso2: "JM", iso3: "JAM", phoneCode: "+1" },
  { country: "Japan", iso2: "JP", iso3: "JPN", phoneCode: "+81" },
  { country: "Jersey", iso2: "JE", iso3: "JEY", phoneCode: "+44" },
  { country: "Jordan", iso2: "JO", iso3: "JOR", phoneCode: "+962" },
  { country: "Kazakhstan", iso2: "KZ", iso3: "KAZ", phoneCode: "+7" },
  { country: "Kenya", iso2: "KE", iso3: "KEN", phoneCode: "+254" },
  { country: "Kiribati", iso2: "KI", iso3: "KIR", phoneCode: "+686" },
  { country: "Kosovo", iso2: "XK", iso3: "UNK", phoneCode: "+383" },
  { country: "Kuwait", iso2: "KW", iso3: "KWT", phoneCode: "+965" },
  { country: "Kyrgyzstan", iso2: "KG", iso3: "KGZ", phoneCode: "+996" },
  { country: "Laos", iso2: "LA", iso3: "LAO", phoneCode: "+856" },
  { country: "Latvia", iso2: "LV", iso3: "LVA", phoneCode: "+371" },
  { country: "Lebanon", iso2: "LB", iso3: "LBN", phoneCode: "+961" },
  { country: "Lesotho", iso2: "LS", iso3: "LSO", phoneCode: "+266" },
  { country: "Liberia", iso2: "LR", iso3: "LBR", phoneCode: "+231" },
  { country: "Libya", iso2: "LY", iso3: "LBY", phoneCode: "+218" },
  { country: "Liechtenstein", iso2: "LI", iso3: "LIE", phoneCode: "+423" },
  { country: "Lithuania", iso2: "LT", iso3: "LTU", phoneCode: "+370" },
  { country: "Luxembourg", iso2: "LU", iso3: "LUX", phoneCode: "+352" },
  { country: "Macau", iso2: "MO", iso3: "MAC", phoneCode: "+853" },
  { country: "Macedonia", iso2: "MK", iso3: "MKD", phoneCode: "+389" },
  { country: "Madagascar", iso2: "MG", iso3: "MDG", phoneCode: "+261" },
  { country: "Malawi", iso2: "MW", iso3: "MWI", phoneCode: "+265" },
  { country: "Malaysia", iso2: "MY", iso3: "MYS", phoneCode: "+60" },
  { country: "Maldives", iso2: "MV", iso3: "MDV", phoneCode: "+960" },
  { country: "Mali", iso2: "ML", iso3: "MLI", phoneCode: "+223" },
  { country: "Malta", iso2: "MT", iso3: "MLT", phoneCode: "+356" },
  { country: "Marshall Islands", iso2: "MH", iso3: "MHL", phoneCode: "+692" },
  { country: "Mauritania", iso2: "MR", iso3: "MRT", phoneCode: "+222" },
  { country: "Mauritius", iso2: "MU", iso3: "MUS", phoneCode: "+230" },
  { country: "Mayotte", iso2: "YT", iso3: "MYT", phoneCode: "+262" },
  { country: "Mexico", iso2: "MX", iso3: "MEX", phoneCode: "+52" },
  { country: "Micronesia", iso2: "FM", iso3: "FSM", phoneCode: "+691" },
  { country: "Moldova", iso2: "MD", iso3: "MDA", phoneCode: "+373" },
  { country: "Monaco", iso2: "MC", iso3: "MCO", phoneCode: "+377" },
  { country: "Mongolia", iso2: "MN", iso3: "MNG", phoneCode: "+976" },
  { country: "Montenegro", iso2: "ME", iso3: "MNE", phoneCode: "+382" },
  { country: "Montserrat", iso2: "MS", iso3: "MSR", phoneCode: "+1" },
  { country: "Morocco", iso2: "MA", iso3: "MAR", phoneCode: "+212" },
  { country: "Mozambique", iso2: "MZ", iso3: "MOZ", phoneCode: "+258" },
  { country: "Myanmar", iso2: "MM", iso3: "MMR", phoneCode: "+95" },
  { country: "Namibia", iso2: "NA", iso3: "NAM", phoneCode: "+264" },
  { country: "Nauru", iso2: "NR", iso3: "NRU", phoneCode: "+674" },
  { country: "Nepal", iso2: "NP", iso3: "NPL", phoneCode: "+977" },
  { country: "Netherlands", iso2: "NL", iso3: "NLD", phoneCode: "+31" },
  { country: "Netherlands Antilles", iso2: "AN", iso3: "ANT", phoneCode: "+599" },
  { country: "New Caledonia", iso2: "NC", iso3: "NCL", phoneCode: "+687" },
  { country: "New Zealand", iso2: "NZ", iso3: "NZL", phoneCode: "+64" },
  { country: "Nicaragua", iso2: "NI", iso3: "NIC", phoneCode: "+505" },
  { country: "Niger", iso2: "NE", iso3: "NER", phoneCode: "+227" },
  { country: "Nigeria", iso2: "NG", iso3: "NGA", phoneCode: "+234" },
  { country: "Niue", iso2: "NU", iso3: "NIU", phoneCode: "+683" },
  { country: "North Korea", iso2: "KP", iso3: "PRK", phoneCode: "+850" },
  { country: "Northern Mariana Islands", iso2: "MP", iso3: "MNP", phoneCode: "+1" },
  { country: "Norway", iso2: "NO", iso3: "NOR", phoneCode: "+47" },
  { country: "Oman", iso2: "OM", iso3: "OMN", phoneCode: "+968" },
  { country: "Pakistan", iso2: "PK", iso3: "PAK", phoneCode: "+92" },
  { country: "Palau", iso2: "PW", iso3: "PLW", phoneCode: "+680" },
  { country: "Palestine", iso2: "PS", iso3: "PSE", phoneCode: "+970" },
  { country: "Panama", iso2: "PA", iso3: "PAN", phoneCode: "+507" },
  { country: "Papua New Guinea", iso2: "PG", iso3: "PNG", phoneCode: "+675" },
  { country: "Paraguay", iso2: "PY", iso3: "PRY", phoneCode: "+595" },
  { country: "Peru", iso2: "PE", iso3: "PER", phoneCode: "+51" },
  { country: "Philippines", iso2: "PH", iso3: "PHL", phoneCode: "+63" },
  { country: "Pitcairn", iso2: "PN", iso3: "PCN", phoneCode: "+64" },
  { country: "Poland", iso2: "PL", iso3: "POL", phoneCode: "+48" },
  { country: "Portugal", iso2: "PT", iso3: "PRT", phoneCode: "+351" },
  { country: "Puerto Rico", iso2: "PR", iso3: "PRI", phoneCode: "+1" },
  { country: "Qatar", iso2: "QA", iso3: "QAT", phoneCode: "+974" },
  { country: "Republic of the Congo", iso2: "CG", iso3: "COG", phoneCode: "+242" },
  { country: "Reunion", iso2: "RE", iso3: "REU", phoneCode: "+262" },
  { country: "Romania", iso2: "RO", iso3: "ROU", phoneCode: "+40" },
  { country: "Russia", iso2: "RU", iso3: "RUS", phoneCode: "+7" },
  { country: "Rwanda", iso2: "RW", iso3: "RWA", phoneCode: "+250" },
  { country: "Saint Barthelemy", iso2: "BL", iso3: "BLM", phoneCode: "+590" },
  { country: "Saint Helena", iso2: "SH", iso3: "SHN", phoneCode: "+290" },
  { country: "Saint Kitts and Nevis", iso2: "KN", iso3: "KNA", phoneCode: "+1" },
  { country: "Saint Lucia", iso2: "LC", iso3: "LCA", phoneCode: "+1" },
  { country: "Saint Martin", iso2: "MF", iso3: "MAF", phoneCode: "+590" },
  { country: "Saint Pierre and Miquelon", iso2: "PM", iso3: "SPM", phoneCode: "+508" },
  { country: "Saint Vincent and the Grenadines", iso2: "VC", iso3: "VCT", phoneCode: "+1" },
  { country: "Samoa", iso2: "WS", iso3: "WSM", phoneCode: "+685" },
  { country: "San Marino", iso2: "SM", iso3: "SMR", phoneCode: "+378" },
  { country: "Sao Tome and Principe", iso2: "ST", iso3: "STP", phoneCode: "+239" },
  { country: "Saudi Arabia", iso2: "SA", iso3: "SAU", phoneCode: "+966" },
  { country: "Senegal", iso2: "SN", iso3: "SEN", phoneCode: "+221" },
  { country: "Serbia", iso2: "RS", iso3: "SRB", phoneCode: "+381" },
  { country: "Seychelles", iso2: "SC", iso3: "SYC", phoneCode: "+248" },
  { country: "Sierra Leone", iso2: "SL", iso3: "SLE", phoneCode: "+232" },
  { country: "Singapore", iso2: "SG", iso3: "SGP", phoneCode: "+65" },
  { country: "Sint Maarten", iso2: "SX", iso3: "SXM", phoneCode: "+1" },
  { country: "Slovakia", iso2: "SK", iso3: "SVK", phoneCode: "+421" },
  { country: "Slovenia", iso2: "SI", iso3: "SVN", phoneCode: "+386" },
  { country: "Solomon Islands", iso2: "SB", iso3: "SLB", phoneCode: "+677" },
  { country: "Somalia", iso2: "SO", iso3: "SOM", phoneCode: "+252" },
  { country: "South Africa", iso2: "ZA", iso3: "ZAF", phoneCode: "+27" },
  { country: "South Korea", iso2: "KR", iso3: "KOR", phoneCode: "+82" },
  { country: "South Sudan", iso2: "SS", iso3: "SSD", phoneCode: "+211" },
  { country: "Spain", iso2: "ES", iso3: "ESP", phoneCode: "+34" },
  { country: "Sri Lanka", iso2: "LK", iso3: "LKA", phoneCode: "+94" },
  { country: "Sudan", iso2: "SD", iso3: "SDN", phoneCode: "+249" },
  { country: "Suriname", iso2: "SR", iso3: "SUR", phoneCode: "+597" },
  { country: "Svalbard and Jan Mayen", iso2: "SJ", iso3: "SJM", phoneCode: "+47" },
  { country: "Swaziland", iso2: "SZ", iso3: "SWZ", phoneCode: "+268" },
  { country: "Sweden", iso2: "SE", iso3: "SWE", phoneCode: "+46" },
  { country: "Switzerland", iso2: "CH", iso3: "CHE", phoneCode: "+41" },
  { country: "Syria", iso2: "SY", iso3: "SYR", phoneCode: "+963" },
  { country: "Taiwan", iso2: "TW", iso3: "TWN", phoneCode: "+886" },
  { country: "Tajikistan", iso2: "TJ", iso3: "TJK", phoneCode: "+992" },
  { country: "Tanzania", iso2: "TZ", iso3: "TZA", phoneCode: "+255" },
  { country: "Thailand", iso2: "TH", iso3: "THA", phoneCode: "+66" },
  { country: "Togo", iso2: "TG", iso3: "TGO", phoneCode: "+228" },
  { country: "Tokelau", iso2: "TK", iso3: "TKL", phoneCode: "+690" },
  { country: "Tonga", iso2: "TO", iso3: "TON", phoneCode: "+676" },
  { country: "Trinidad and Tobago", iso2: "TT", iso3: "TTO", phoneCode: "+1" },
  { country: "Tunisia", iso2: "TN", iso3: "TUN", phoneCode: "+216" },
  { country: "Turkey", iso2: "TR", iso3: "TUR", phoneCode: "+90" },
  { country: "Turkmenistan", iso2: "TM", iso3: "TKM", phoneCode: "+993" },
  { country: "Turks and Caicos Islands", iso2: "TC", iso3: "TCA", phoneCode: "+1" },
  { country: "Tuvalu", iso2: "TV", iso3: "TUV", phoneCode: "+688" },
  { country: "U.S. Virgin Islands", iso2: "VI", iso3: "VIR", phoneCode: "+1" },
  { country: "Uganda", iso2: "UG", iso3: "UGA", phoneCode: "+256" },
  { country: "Ukraine", iso2: "UA", iso3: "UKR", phoneCode: "+380" },
  { country: "United Arab Emirates", iso2: "AE", iso3: "ARE", phoneCode: "+971" },
  { country: "United Kingdom", iso2: "GB", iso3: "GBR", phoneCode: "+44" },
  { country: "United States", iso2: "US", iso3: "USA", phoneCode: "+1" },
  { country: "Uruguay", iso2: "UY", iso3: "URY", phoneCode: "+598" },
  { country: "Uzbekistan", iso2: "UZ", iso3: "UZB", phoneCode: "+998" },
  { country: "Vanuatu", iso2: "VU", iso3: "VUT", phoneCode: "+678" },
  { country: "Vatican", iso2: "VA", iso3: "VAT", phoneCode: "+379" },
  { country: "Venezuela", iso2: "VE", iso3: "VEN", phoneCode: "+58" },
  { country: "Vietnam", iso2: "VN", iso3: "VNM", phoneCode: "+84" },
  { country: "Wallis and Futuna", iso2: "WF", iso3: "WLF", phoneCode: "+681" },
  { country: "Western Sahara", iso2: "EH", iso3: "ESH", phoneCode: "+212" },
  { country: "Yemen", iso2: "YE", iso3: "YEM", phoneCode: "+967" },
  { country: "Zambia", iso2: "ZM", iso3: "ZMB", phoneCode: "+260" },
  { country: "Zimbabwe", iso2: "ZW", iso3: "ZWE", phoneCode: "+263" }
];

export const PHONE_CODES = [
  "+93", "+355", "+213", "+1", "+376", "+244", "+1", "+672", "+1", "+54",
  "+374", "+297", "+61", "+43", "+994", "+1", "+973", "+880", "+1", "+375",
  "+32", "+501", "+229", "+1", "+975", "+591", "+387", "+267", "+55", "+246",
  "+1", "+673", "+359", "+226", "+257", "+855", "+237", "+1", "+238", "+1",
  "+236", "+235", "+56", "+86", "+61", "+61", "+57", "+269", "+682", "+506",
  "+385", "+53", "+599", "+357", "+420", "+243", "+45", "+253", "+1", "+1",
  "+670", "+593", "+20", "+503", "+240", "+291", "+372", "+251", "+500", "+298",
  "+679", "+358", "+33", "+689", "+241", "+220", "+995", "+49", "+233", "+350",
  "+30", "+299", "+1", "+1", "+502", "+44", "+224", "+245", "+592", "+509",
  "+504", "+852", "+36", "+354", "+91", "+62", "+98", "+964", "+353", "+44",
  "+972", "+39", "+225", "+1", "+81", "+44", "+962", "+7", "+254", "+686",
  "+383", "+965", "+996", "+856", "+371", "+961", "+266", "+231", "+218", "+423",
  "+370", "+352", "+853", "+389", "+261", "+265", "+60", "+960", "+223", "+356",
  "+692", "+222", "+230", "+262", "+52", "+691", "+373", "+377", "+976", "+382",
  "+1", "+212", "+258", "+95", "+264", "+674", "+977", "+31", "+599", "+687",
  "+64", "+505", "+227", "+234", "+683", "+850", "+1", "+47", "+968", "+92",
  "+680", "+970", "+507", "+675", "+595", "+51", "+63", "+64", "+48", "+351",
  "+1", "+974", "+242", "+262", "+40", "+7", "+250", "+590", "+290", "+1",
  "+1", "+590", "+508", "+1", "+685", "+378", "+239", "+966", "+221", "+381",
  "+248", "+232", "+65", "+1", "+421", "+386", "+677", "+252", "+27", "+82",
  "+211", "+34", "+94", "+249", "+597", "+47", "+268", "+46", "+41", "+963",
  "+886", "+992", "+255", "+66", "+228", "+690", "+676", "+1", "+216", "+90",
  "+993", "+1", "+688", "+1", "+256", "+380", "+971", "+44", "+1", "+598",
  "+998", "+678", "+379", "+58", "+84", "+681", "+212", "+967", "+260", "+263"
];
